Repository KIMgyeongmIN00/out-source-project, pull requests merged in 2025-02, with the labels that each got.

#4 chore/#3 build test action
  .github/workflows/build_test.yml
Labels: ⚙ Setting

#12 Feature/#5 sidebar UI
  eslint.config.js
  package.json
  pnpm-lock.yaml
  src/components/layouts/root-layout.jsx
  src/components/layouts/sidebar.jsx
  src/components/layouts/sidebar/auth-sign-panel.jsx
  src/components/layouts/sidebar/sidebar.jsx
  src/components/ui/button.jsx
  src/components/ui/input.jsx
  src/styles/globals.css
Labels: 🎨 Styles

#11 feature/#6 카카오맵 Home 페이지에 추가
  .gitignore
  .prettierrc
  package.json
  pnpm-lock.yaml
  src/config/router.jsx
  src/constants/app-key.js
  src/constants/map-scale.js
  src/lib/apis/map.api.js
  src/pages/home.jsx
Labels: ⚙ Setting, ✨ Feature, 📬 API

#15 Feature/#13 로그인 및 회원가입 로직 구현
  src/components/layouts/sidebar/sidebar.jsx
  src/components/layouts/sidebar/sign-error-panel.jsx
  src/components/layouts/sidebar/sign-in-form.jsx
  src/components/layouts/sidebar/sign-panel.jsx
  src/components/layouts/sidebar/sign-up-form.jsx
  src/components/ui/input.jsx
  src/lib/hooks/use-sign-in-form.hook.js
  src/lib/hooks/use-sign-up-form.hook.js
  src/lib/utils/auth-validate.util.js
Labels: ✨ Feature

#16 feat:#7 supabase api 연결 및 인증 전역 상태 구현
  package.json
  pnpm-lock.yaml
  src/lib/apis/auth.api.js
  src/lib/apis/axios.api.js
  src/lib/apis/plan.api.js
  src/lib/apis/supabase.api.js
  src/stores/auth.store.js
Labels: ✨ Feature

#20 Feature/#17 로그인 상태의 사이드바 UI
  .gitignore
  package.json
  pnpm-lock.yaml
  public/default_profile.png
  src/components/layouts/sidebar/plan-panel.jsx
  src/components/layouts/sidebar/sidebar.jsx
  src/components/layouts/sidebar/user-panel.jsx
  src/components/ui/button.jsx
Labels: 🎨 Styles

#18 feat/#14 현재 사용자 위치 표시하는 기능 추가
  src/pages/home.jsx
  src/stores/map.store.js
Labels: ✨ Feature, 📬 API

#23 Feature/#19 routing protect
  package.json
  pnpm-lock.yaml
  src/components/features/protected-router/warning-alert.jsx
  src/components/ui/alert-dialog.jsx
  src/config/protected-router.jsx
  src/config/router.jsx
Labels: 🎨 Styles, ✨ Feature
