Repository KIMgyeongmIN00/out-source-project, pull requests merged in 2025-03, with the labels that each got.

#24 Feature/#9 Modal UI 만들기
  components.json
  package.json
  pnpm-lock.yaml
  src/components/features/modal/edit-modal.jsx
  src/components/features/modal/write-modal.jsx
  src/components/layouts/modal/modal-date.jsx
  src/components/layouts/modal/modal-memo.jsx
  src/components/layouts/modal/modal-position.jsx
  src/components/layouts/modal/modal-title.jsx
  src/components/layouts/modal/modal.jsx
  src/components/ui/button.jsx
  src/components/ui/dialog.jsx
  src/components/ui/textarea.jsx
  src/constants/modal-constants.js
  src/lib/apis/auth.api.js
  src/lib/hooks/useForm.jsx
  src/pages/home.jsx
Labels: 🎨 Styles, ✨ Feature

#26 Feature/#21 로그인 회원가입 api
  package.json
  pnpm-lock.yaml
  src/App.jsx
  src/components/layouts/sidebar/plan-panel.jsx
  src/components/layouts/sidebar/sidebar.jsx
  src/components/layouts/sidebar/user-panel.jsx
  src/lib/apis/auth.api.js
  src/lib/hooks/use-auth-subscriber.js
  src/lib/hooks/use-sign-in-form.hook.js
  src/lib/hooks/use-sign-up-form.hook.js
  src/lib/utils/sweet-alert.util.js
  src/stores/auth.store.js
Labels: ✨ Feature, 📬 API

#28 Feature/#22 맵 모달창 주소 가져오기
  package.json
  pnpm-lock.yaml
  src/App.jsx
  src/components/map/map-address-modal.jsx
  src/components/map/map-marker.jsx
  src/constants/app-key.js
  src/lib/apis/axios.api.js
  src/lib/apis/map.api.js
  src/pages/home.jsx
Labels: ✨ Feature, 📬 API

#30 Feature/#29 이전 일정 불러온 후 렌더링
  src/components/features/profile/profile-form.jsx
  src/lib/hooks/use-get-all-plans-usequery.js
  src/pages/profile.jsx
Labels: 📬 API

#38 Feature/#35 사이드바에 일정 표시
  src/App.jsx
  src/components/layouts/sidebar/plan-card.jsx
  src/components/layouts/sidebar/plan-panel.jsx
  src/components/layouts/sidebar/sidebar.jsx
  src/constants/query-keys.js
  src/lib/apis/plan.api.js
  src/lib/hooks/use-auth-subscriber.hook.js
  src/lib/hooks/use-get-upcoming-plans-query.hook.js
Labels: ✨ Feature, 📬 API

#39 Feature/#32 일정추가 후 마커 표시
  src/components/features/modal/edit-modal.jsx
  src/components/features/modal/write-modal.jsx
  src/components/layouts/modal/modal-date.jsx
  src/components/layouts/modal/modal-memo.jsx
  src/components/layouts/modal/modal-position.jsx
  src/components/layouts/modal/modal-title.jsx
  src/components/layouts/modal/modal.jsx
  src/components/map/map-address-modal.jsx
  src/components/map/map-plans-marker.jsx
  src/components/ui/button.jsx
  src/lib/hooks/useForm.jsx
  src/pages/home.jsx
Labels: ✨ Feature

#42 Feature/#34 맵 검색 기능 추가
  src/components/features/map/map-address-modal.jsx
  src/components/features/map/map-marker.jsx
  src/components/features/map/map-plans-marker.jsx
  src/components/features/map/map-search-box.jsx
  src/components/features/map/map-search-result-item.jsx
  src/components/features/map/map-search-results.jsx
  src/components/features/map/map-search.jsx
  src/components/layouts/modal/modal-position.jsx
  src/lib/apis/axios.api.js
  src/lib/apis/map.api.js
  src/pages/home.jsx
  src/stores/map.store.js
Labels: ✨ Feature, 📬 API

#46 Refactor/#41 프로필 페이지 코드 리팩토링
  src/App.jsx
  src/components/features/profile/profile-form.jsx
  src/constants/query-keys.js
  src/lib/hooks/use-auth-subscriber.hook.js
  src/lib/hooks/use-get-all-plans-query.js
  src/lib/hooks/use-update-nickname-mutation.js
  src/lib/hooks/use-update-profile-image-mutation.js
  src/lib/hooks/use-update-profile-mutation.js
Labels: 🔨 Refactor

#49 refactor:#27 리팩토링 완료
  src/components/features/map/map-address-modal.jsx
  src/components/features/map/map-plans-marker.jsx
  src/components/features/map/map-plans-modal.jsx
  src/components/features/map/map-search.jsx
  src/components/features/modal/edit-modal.jsx
  src/components/features/modal/write-modal.jsx
  src/components/features/profile/profile-form.jsx
  src/components/features/profile/profile-most-visited-place.jsx
  src/components/features/profile/profile-pagination.jsx
  src/components/layouts/modal/modal-memo.jsx
  src/components/layouts/sidebar/plan-panel.jsx
  src/components/layouts/sidebar/sidebar.jsx
  src/components/layouts/sidebar/sign-in-form.jsx
  src/components/layouts/sidebar/sign-up-form.jsx
  src/components/ui/alert-dialog.jsx
  src/components/ui/dialog.jsx
  src/constants/query-key.js
  src/constants/query-keys.js
  src/lib/hooks/map/use-map-address.hook.js
  src/lib/hooks/map/use-map-plans-modal.hook.js
  src/lib/hooks/map/use-map-search.hook.js
  src/lib/hooks/marker/use-get-all-plans-to-marker-query.js
  src/lib/hooks/modal/use-edit-plan.hook.js
  src/lib/hooks/modal/use-write-plan.hook.js
  src/lib/hooks/profile/use-fetch-all-plans-on-page.hook.js
  src/lib/hooks/profile/use-profile-edit.hook.js
  src/lib/hooks/profile/use-rank-address-query.js
  src/lib/hooks/profile/use-update-nickname-mutation.js
  src/lib/hooks/profile/use-update-profile-image-mutation.js
  src/lib/hooks/sidebar/use-get-upcoming-plans-query.hook.js
  src/lib/hooks/sidebar/use-sign-in-form.hook.js
  src/lib/hooks/sidebar/use-sign-up-form.hook.js
  src/lib/hooks/use-handle-plans-query.js
  src/lib/hooks/use-home.js
  src/lib/hooks/use-page-plans.hook.js
  src/lib/utils/date-trim.utill.js
  src/pages/home.jsx
  src/pages/profile.jsx
Labels: 🔨 Refactor

#59 Feature/#50 사이드바의 일정에 click 이벤트 넣기
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  package.json
  pnpm-lock.yaml
  src/components/features/map/map-plans-modal.jsx
  src/components/features/modal/edit-modal.jsx
  src/components/features/profile/profile-most-visited-place.jsx
  src/components/features/profile/profile-pagination.jsx
  src/components/layouts/modal/modal-date.jsx
  src/components/layouts/modal/modal-position.jsx
  src/components/layouts/modal/modal-title.jsx
  src/components/layouts/sidebar/plan-panel.jsx
  src/components/layouts/sidebar/sidebar.jsx
  src/components/layouts/sidebar/user-panel.jsx
  src/components/ui/plan-card.jsx
  src/components/ui/textarea.jsx
  src/constants/query-keys.js
  src/constants/query-time.js
  src/lib/apis/axios.api.js
  src/lib/apis/supabase.api.js
  src/lib/hooks/map/use-map-address.hook.js
  src/lib/hooks/map/use-map-plans-modal.hook.js
  src/lib/hooks/marker/use-get-all-plans-to-marker-query.js
  src/lib/hooks/modal/use-edit-plan.hook.js
  src/lib/hooks/modal/use-write-plan.hook.js
  src/lib/hooks/profile/use-fetch-all-plans-on-page.hook.js
  src/lib/hooks/profile/use-profile-edit.hook.js
  src/lib/hooks/use-handle-plans-query.js
  src/lib/hooks/use-page-plans.hook.js
  src/lib/hooks/useForm.jsx
  src/lib/utils.js
Labels: ✨ Feature

#61 Update README.md
  README.md
Labels: 📃 Docs
